DROP TABLE IF EXISTS spells CASCADE;

CREATE TABLE spells (
    index varchar(50) PRIMARY KEY,
    name varchar(50),
    url varchar(250)
);

DROP TABLE IF EXISTS wizards CASCADE;

CREATE TABLE wizards (
    index SERIAL PRIMARY KEY,
    name varchar(50),
    spell_id varchar(50) REFERENCES spells(index)
);

INSERT INTO spells (index, name, url) VALUES ('acid-arrow', 'Acid Arrow', '/api/spells/acid-arrow');
INSERT INTO spells (index, name, url) VALUES ('acid-splash', 'Acid Splash', '/api/spells/acid-splash');
INSERT INTO spells (index, name, url) VALUES ('aid', 'Aid', '/api/spells/aid');
INSERT INTO spells (index, name, url) VALUES ('alarm', 'Alarm', '/api/spells/alarm');
INSERT INTO spells (index, name, url) VALUES ('alter-self', 'Alter Self', '/api/spells/alter-self');
INSERT INTO spells (index, name, url) VALUES ('animal-friendship', 'Animal Friendship', '/api/spells/animal-friendship');
INSERT INTO spells (index, name, url) VALUES ('animal-messenger', 'Animal Messenger', '/api/spells/animal-messenger');
INSERT INTO spells (index, name, url) VALUES ('animal-shapes', 'Animal Shapes', '/api/spells/animal-shapes');
INSERT INTO spells (index, name, url) VALUES ('animate-dead', 'Animate Dead', '/api/spells/animate-dead');
INSERT INTO spells (index, name, url) VALUES ('animate-objects', 'Animate Objects', '/api/spells/animate-objects');
INSERT INTO spells (index, name, url) VALUES ('antilife-shell', 'Antilife Shell', '/api/spells/antilife-shell');
INSERT INTO spells (index, name, url) VALUES ('antimagic-field', 'Antimagic Field', '/api/spells/antimagic-field');
INSERT INTO spells (index, name, url) VALUES ('antipathy-sympathy', 'Antipathy/Sympathy', '/api/spells/antipathy-sympathy');
INSERT INTO spells (index, name, url) VALUES ('arcane-eye', 'Arcane Eye', '/api/spells/arcane-eye');
INSERT INTO spells (index, name, url) VALUES ('arcane-hand', 'Arcane Hand', '/api/spells/arcane-hand');
INSERT INTO spells (index, name, url) VALUES ('arcane-lock', 'Arcane Lock', '/api/spells/arcane-lock');
INSERT INTO spells (index, name, url) VALUES ('arcane-sword', 'Arcane Sword', '/api/spells/arcane-sword');
INSERT INTO spells (index, name, url) VALUES ('arcanists-magic-aura', 'Arcanists Magic Aura', '/api/spells/arcanists-magic-aura');
INSERT INTO spells (index, name, url) VALUES ('astral-projection', 'Astral Projection', '/api/spells/astral-projection');
INSERT INTO spells (index, name, url) VALUES ('augury', 'Augury', '/api/spells/augury');
INSERT INTO spells (index, name, url) VALUES ('awaken', 'Awaken', '/api/spells/awaken');
INSERT INTO spells (index, name, url) VALUES ('bane', 'Bane', '/api/spells/bane');
INSERT INTO spells (index, name, url) VALUES ('banishment', 'Banishment', '/api/spells/banishment');
INSERT INTO spells (index, name, url) VALUES ('barkskin', 'Barkskin', '/api/spells/barkskin');
INSERT INTO spells (index, name, url) VALUES ('beacon-of-hope', 'Beacon of Hope', '/api/spells/beacon-of-hope');
INSERT INTO spells (index, name, url) VALUES ('bestow-curse', 'Bestow Curse', '/api/spells/bestow-curse');
INSERT INTO spells (index, name, url) VALUES ('black-tentacles', 'Black Tentacles', '/api/spells/black-tentacles');
INSERT INTO spells (index, name, url) VALUES ('blade-barrier', 'Blade Barrier', '/api/spells/blade-barrier');
INSERT INTO spells (index, name, url) VALUES ('bless', 'Bless', '/api/spells/bless');
INSERT INTO spells (index, name, url) VALUES ('blight', 'Blight', '/api/spells/blight');
INSERT INTO spells (index, name, url) VALUES ('blindness-deafness', 'Blindness/Deafness', '/api/spells/blindness-deafness');
INSERT INTO spells (index, name, url) VALUES ('blink', 'Blink', '/api/spells/blink');
INSERT INTO spells (index, name, url) VALUES ('blur', 'Blur', '/api/spells/blur');
INSERT INTO spells (index, name, url) VALUES ('branding-smite', 'Branding Smite', '/api/spells/branding-smite');
INSERT INTO spells (index, name, url) VALUES ('burning-hands', 'Burning Hands', '/api/spells/burning-hands');
INSERT INTO spells (index, name, url) VALUES ('call-lightning', 'Call Lightning', '/api/spells/call-lightning');
INSERT INTO spells (index, name, url) VALUES ('calm-emotions', 'Calm Emotions', '/api/spells/calm-emotions');
INSERT INTO spells (index, name, url) VALUES ('chain-lightning', 'Chain Lightning', '/api/spells/chain-lightning');
INSERT INTO spells (index, name, url) VALUES ('charm-person', 'Charm Person', '/api/spells/charm-person');
INSERT INTO spells (index, name, url) VALUES ('chill-touch', 'Chill Touch', '/api/spells/chill-touch');
INSERT INTO spells (index, name, url) VALUES ('circle-of-death', 'Circle of Death', '/api/spells/circle-of-death');
INSERT INTO spells (index, name, url) VALUES ('clairvoyance', 'Clairvoyance', '/api/spells/clairvoyance');
INSERT INTO spells (index, name, url) VALUES ('clone', 'Clone', '/api/spells/clone');
INSERT INTO spells (index, name, url) VALUES ('cloudkill', 'Cloudkill', '/api/spells/cloudkill');
INSERT INTO spells (index, name, url) VALUES ('color-spray', 'Color Spray', '/api/spells/color-spray');
INSERT INTO spells (index, name, url) VALUES ('command', 'Command', '/api/spells/command');
INSERT INTO spells (index, name, url) VALUES ('commune', 'Commune', '/api/spells/commune');
INSERT INTO spells (index, name, url) VALUES ('commune-with-nature', 'Commune With Nature', '/api/spells/commune-with-nature');
INSERT INTO spells (index, name, url) VALUES ('comprehend-languages', 'Comprehend Languages', '/api/spells/comprehend-languages');
INSERT INTO spells (index, name, url) VALUES ('compulsion', 'Compulsion', '/api/spells/compulsion');
INSERT INTO spells (index, name, url) VALUES ('cone-of-cold', 'Cone of Cold', '/api/spells/cone-of-cold');
INSERT INTO spells (index, name, url) VALUES ('confusion', 'Confusion', '/api/spells/confusion');
INSERT INTO spells (index, name, url) VALUES ('conjure-animals', 'Conjure Animals', '/api/spells/conjure-animals');
INSERT INTO spells (index, name, url) VALUES ('conjure-celestial', 'Conjure Celestial', '/api/spells/conjure-celestial');
INSERT INTO spells (index, name, url) VALUES ('conjure-elemental', 'Conjure Elemental', '/api/spells/conjure-elemental');
INSERT INTO spells (index, name, url) VALUES ('conjure-fey', 'Conjure Fey', '/api/spells/conjure-fey');
INSERT INTO spells (index, name, url) VALUES ('conjure-minor-elementals', 'Conjure Minor Elementals', '/api/spells/conjure-minor-elementals');
INSERT INTO spells (index, name, url) VALUES ('conjure-woodland-beings', 'Conjure Woodland Beings', '/api/spells/conjure-woodland-beings');
INSERT INTO spells (index, name, url) VALUES ('contact-other-plane', 'Contact Other Plane', '/api/spells/contact-other-plane');
INSERT INTO spells (index, name, url) VALUES ('contagion', 'Contagion', '/api/spells/contagion');
INSERT INTO spells (index, name, url) VALUES ('contingency', 'Contingency', '/api/spells/contingency');
INSERT INTO spells (index, name, url) VALUES ('continual-flame', 'Continual Flame', '/api/spells/continual-flame');
INSERT INTO spells (index, name, url) VALUES ('control-water', 'Control Water', '/api/spells/control-water');
INSERT INTO spells (index, name, url) VALUES ('control-weather', 'Control Weather', '/api/spells/control-weather');
INSERT INTO spells (index, name, url) VALUES ('counterspell', 'Counterspell', '/api/spells/counterspell');
INSERT INTO spells (index, name, url) VALUES ('create-food-and-water', 'Create Food and Water', '/api/spells/create-food-and-water');
INSERT INTO spells (index, name, url) VALUES ('create-or-destroy-water', 'Create or Destroy Water', '/api/spells/create-or-destroy-water');
INSERT INTO spells (index, name, url) VALUES ('create-undead', 'Create Undead', '/api/spells/create-undead');
INSERT INTO spells (index, name, url) VALUES ('creation', 'Creation', '/api/spells/creation');
INSERT INTO spells (index, name, url) VALUES ('cure-wounds', 'Cure Wounds', '/api/spells/cure-wounds');
INSERT INTO spells (index, name, url) VALUES ('dancing-lights', 'Dancing Lights', '/api/spells/dancing-lights');
INSERT INTO spells (index, name, url) VALUES ('darkness', 'Darkness', '/api/spells/darkness');
INSERT INTO spells (index, name, url) VALUES ('darkvision', 'Darkvision', '/api/spells/darkvision');
INSERT INTO spells (index, name, url) VALUES ('daylight', 'Daylight', '/api/spells/daylight');
INSERT INTO spells (index, name, url) VALUES ('death-ward', 'Death Ward', '/api/spells/death-ward');
INSERT INTO spells (index, name, url) VALUES ('delayed-blast-fireball', 'Delayed Blast Fireball', '/api/spells/delayed-blast-fireball');
INSERT INTO spells (index, name, url) VALUES ('demiplane', 'Demiplane', '/api/spells/demiplane');
INSERT INTO spells (index, name, url) VALUES ('detect-evil-and-good', 'Detect Evil and Good', '/api/spells/detect-evil-and-good');
INSERT INTO spells (index, name, url) VALUES ('detect-magic', 'Detect Magic', '/api/spells/detect-magic');
INSERT INTO spells (index, name, url) VALUES ('detect-poison-and-disease', 'Detect Poison and Disease', '/api/spells/detect-poison-and-disease');
INSERT INTO spells (index, name, url) VALUES ('detect-thoughts', 'Detect Thoughts', '/api/spells/detect-thoughts');
INSERT INTO spells (index, name, url) VALUES ('dimension-door', 'Dimension Door', '/api/spells/dimension-door');
INSERT INTO spells (index, name, url) VALUES ('disguise-self', 'Disguise Self', '/api/spells/disguise-self');
INSERT INTO spells (index, name, url) VALUES ('disintegrate', 'Disintegrate', '/api/spells/disintegrate');
INSERT INTO spells (index, name, url) VALUES ('dispel-evil-and-good', 'Dispel Evil and Good', '/api/spells/dispel-evil-and-good');
INSERT INTO spells (index, name, url) VALUES ('dispel-magic', 'Dispel Magic', '/api/spells/dispel-magic');
INSERT INTO spells (index, name, url) VALUES ('divination', 'Divination', '/api/spells/divination');
INSERT INTO spells (index, name, url) VALUES ('divine-favor', 'Divine Favor', '/api/spells/divine-favor');
INSERT INTO spells (index, name, url) VALUES ('divine-word', 'Divine Word', '/api/spells/divine-word');
INSERT INTO spells (index, name, url) VALUES ('dominate-beast', 'Dominate Beast', '/api/spells/dominate-beast');
INSERT INTO spells (index, name, url) VALUES ('dominate-monster', 'Dominate Monster', '/api/spells/dominate-monster');
INSERT INTO spells (index, name, url) VALUES ('dominate-person', 'Dominate Person', '/api/spells/dominate-person');
INSERT INTO spells (index, name, url) VALUES ('dream', 'Dream', '/api/spells/dream');
INSERT INTO spells (index, name, url) VALUES ('druidcraft', 'Druidcraft', '/api/spells/druidcraft');
INSERT INTO spells (index, name, url) VALUES ('earthquake', 'Earthquake', '/api/spells/earthquake');
INSERT INTO spells (index, name, url) VALUES ('eldritch-blast', 'Eldritch Blast', '/api/spells/eldritch-blast');
INSERT INTO spells (index, name, url) VALUES ('enhance-ability', 'Enhance Ability', '/api/spells/enhance-ability');
INSERT INTO spells (index, name, url) VALUES ('enlarge-reduce', 'Enlarge/Reduce', '/api/spells/enlarge-reduce');
INSERT INTO spells (index, name, url) VALUES ('entangle', 'Entangle', '/api/spells/entangle');
INSERT INTO spells (index, name, url) VALUES ('enthrall', 'Enthrall', '/api/spells/enthrall');
INSERT INTO spells (index, name, url) VALUES ('etherealness', 'Etherealness', '/api/spells/etherealness');
INSERT INTO spells (index, name, url) VALUES ('expeditious-retreat', 'Expeditious Retreat', '/api/spells/expeditious-retreat');
INSERT INTO spells (index, name, url) VALUES ('eyebite', 'Eyebite', '/api/spells/eyebite');
INSERT INTO spells (index, name, url) VALUES ('fabricate', 'Fabricate', '/api/spells/fabricate');
INSERT INTO spells (index, name, url) VALUES ('faerie-fire', 'Faerie Fire', '/api/spells/faerie-fire');
INSERT INTO spells (index, name, url) VALUES ('faithful-hound', 'Faithful Hound', '/api/spells/faithful-hound');
INSERT INTO spells (index, name, url) VALUES ('false-life', 'False Life', '/api/spells/false-life');
INSERT INTO spells (index, name, url) VALUES ('fear', 'Fear', '/api/spells/fear');
INSERT INTO spells (index, name, url) VALUES ('feather-fall', 'Feather Fall', '/api/spells/feather-fall');
INSERT INTO spells (index, name, url) VALUES ('feeblemind', 'Feeblemind', '/api/spells/feeblemind');
INSERT INTO spells (index, name, url) VALUES ('find-familiar', 'Find Familiar', '/api/spells/find-familiar');
INSERT INTO spells (index, name, url) VALUES ('find-steed', 'Find Steed', '/api/spells/find-steed');
INSERT INTO spells (index, name, url) VALUES ('find-the-path', 'Find the Path', '/api/spells/find-the-path');
INSERT INTO spells (index, name, url) VALUES ('find-traps', 'Find Traps', '/api/spells/find-traps');
INSERT INTO spells (index, name, url) VALUES ('finger-of-death', 'Finger of Death', '/api/spells/finger-of-death');
INSERT INTO spells (index, name, url) VALUES ('fire-bolt', 'Fire Bolt', '/api/spells/fire-bolt');
INSERT INTO spells (index, name, url) VALUES ('fire-shield', 'Fire Shield', '/api/spells/fire-shield');
INSERT INTO spells (index, name, url) VALUES ('fire-storm', 'Fire Storm', '/api/spells/fire-storm');
INSERT INTO spells (index, name, url) VALUES ('fireball', 'Fireball', '/api/spells/fireball');
INSERT INTO spells (index, name, url) VALUES ('flame-blade', 'Flame Blade', '/api/spells/flame-blade');
INSERT INTO spells (index, name, url) VALUES ('flame-strike', 'Flame Strike', '/api/spells/flame-strike');
INSERT INTO spells (index, name, url) VALUES ('flaming-sphere', 'Flaming Sphere', '/api/spells/flaming-sphere');
INSERT INTO spells (index, name, url) VALUES ('flesh-to-stone', 'Flesh to Stone', '/api/spells/flesh-to-stone');
INSERT INTO spells (index, name, url) VALUES ('floating-disk', 'Floating Disk', '/api/spells/floating-disk');
INSERT INTO spells (index, name, url) VALUES ('fly', 'Fly', '/api/spells/fly');
INSERT INTO spells (index, name, url) VALUES ('fog-cloud', 'Fog Cloud', '/api/spells/fog-cloud');
INSERT INTO spells (index, name, url) VALUES ('forbiddance', 'Forbiddance', '/api/spells/forbiddance');
INSERT INTO spells (index, name, url) VALUES ('forcecage', 'Forcecage', '/api/spells/forcecage');
INSERT INTO spells (index, name, url) VALUES ('foresight', 'Foresight', '/api/spells/foresight');
INSERT INTO spells (index, name, url) VALUES ('freedom-of-movement', 'Freedom of Movement', '/api/spells/freedom-of-movement');
INSERT INTO spells (index, name, url) VALUES ('freezing-sphere', 'Freezing Sphere', '/api/spells/freezing-sphere');
INSERT INTO spells (index, name, url) VALUES ('gaseous-form', 'Gaseous Form', '/api/spells/gaseous-form');
INSERT INTO spells (index, name, url) VALUES ('gate', 'Gate', '/api/spells/gate');
INSERT INTO spells (index, name, url) VALUES ('geas', 'Geas', '/api/spells/geas');
INSERT INTO spells (index, name, url) VALUES ('gentle-repose', 'Gentle Repose', '/api/spells/gentle-repose');
INSERT INTO spells (index, name, url) VALUES ('giant-insect', 'Giant Insect', '/api/spells/giant-insect');
INSERT INTO spells (index, name, url) VALUES ('glibness', 'Glibness', '/api/spells/glibness');
INSERT INTO spells (index, name, url) VALUES ('globe-of-invulnerability', 'Globe of Invulnerability', '/api/spells/globe-of-invulnerability');
INSERT INTO spells (index, name, url) VALUES ('glyph-of-warding', 'Glyph of Warding', '/api/spells/glyph-of-warding');
INSERT INTO spells (index, name, url) VALUES ('goodberry', 'Goodberry', '/api/spells/goodberry');
INSERT INTO spells (index, name, url) VALUES ('grease', 'Grease', '/api/spells/grease');
INSERT INTO spells (index, name, url) VALUES ('greater-invisibility', 'Greater Invisibility', '/api/spells/greater-invisibility');
INSERT INTO spells (index, name, url) VALUES ('greater-restoration', 'Greater Restoration', '/api/spells/greater-restoration');
INSERT INTO spells (index, name, url) VALUES ('guardian-of-faith', 'Guardian of Faith', '/api/spells/guardian-of-faith');
INSERT INTO spells (index, name, url) VALUES ('guards-and-wards', 'Guards and Wards', '/api/spells/guards-and-wards');
INSERT INTO spells (index, name, url) VALUES ('guidance', 'Guidance', '/api/spells/guidance');
INSERT INTO spells (index, name, url) VALUES ('guiding-bolt', 'Guiding Bolt', '/api/spells/guiding-bolt');
INSERT INTO spells (index, name, url) VALUES ('gust-of-wind', 'Gust of Wind', '/api/spells/gust-of-wind');
INSERT INTO spells (index, name, url) VALUES ('hallow', 'Hallow', '/api/spells/hallow');
INSERT INTO spells (index, name, url) VALUES ('hallucinatory-terrain', 'Hallucinatory Terrain', '/api/spells/hallucinatory-terrain');
INSERT INTO spells (index, name, url) VALUES ('harm', 'Harm', '/api/spells/harm');
INSERT INTO spells (index, name, url) VALUES ('haste', 'Haste', '/api/spells/haste');
INSERT INTO spells (index, name, url) VALUES ('heal', 'Heal', '/api/spells/heal');
INSERT INTO spells (index, name, url) VALUES ('healing-word', 'Healing Word', '/api/spells/healing-word');
INSERT INTO spells (index, name, url) VALUES ('heat-metal', 'Heat Metal', '/api/spells/heat-metal');
INSERT INTO spells (index, name, url) VALUES ('hellish-rebuke', 'Hellish Rebuke', '/api/spells/hellish-rebuke');
INSERT INTO spells (index, name, url) VALUES ('heroes-feast', 'Heroes Feast', '/api/spells/heroes-feast');
INSERT INTO spells (index, name, url) VALUES ('heroism', 'Heroism', '/api/spells/heroism');
INSERT INTO spells (index, name, url) VALUES ('hideous-laughter', 'Hideous Laughter', '/api/spells/hideous-laughter');
INSERT INTO spells (index, name, url) VALUES ('hold-monster', 'Hold Monster', '/api/spells/hold-monster');
INSERT INTO spells (index, name, url) VALUES ('hold-person', 'Hold Person', '/api/spells/hold-person');
INSERT INTO spells (index, name, url) VALUES ('holy-aura', 'Holy Aura', '/api/spells/holy-aura');
INSERT INTO spells (index, name, url) VALUES ('hunters-mark', 'Hunters Mark', '/api/spells/hunters-mark');
INSERT INTO spells (index, name, url) VALUES ('hypnotic-pattern', 'Hypnotic Pattern', '/api/spells/hypnotic-pattern');
INSERT INTO spells (index, name, url) VALUES ('ice-storm', 'Ice Storm', '/api/spells/ice-storm');
INSERT INTO spells (index, name, url) VALUES ('identify', 'Identify', '/api/spells/identify');
INSERT INTO spells (index, name, url) VALUES ('illusory-script', 'Illusory Script', '/api/spells/illusory-script');
INSERT INTO spells (index, name, url) VALUES ('imprisonment', 'Imprisonment', '/api/spells/imprisonment');
INSERT INTO spells (index, name, url) VALUES ('incendiary-cloud', 'Incendiary Cloud', '/api/spells/incendiary-cloud');
INSERT INTO spells (index, name, url) VALUES ('inflict-wounds', 'Inflict Wounds', '/api/spells/inflict-wounds');
INSERT INTO spells (index, name, url) VALUES ('insect-plague', 'Insect Plague', '/api/spells/insect-plague');
INSERT INTO spells (index, name, url) VALUES ('instant-summons', 'Instant Summons', '/api/spells/instant-summons');
INSERT INTO spells (index, name, url) VALUES ('invisibility', 'Invisibility', '/api/spells/invisibility');
INSERT INTO spells (index, name, url) VALUES ('irresistible-dance', 'Irresistible Dance', '/api/spells/irresistible-dance');
INSERT INTO spells (index, name, url) VALUES ('jump', 'Jump', '/api/spells/jump');
INSERT INTO spells (index, name, url) VALUES ('knock', 'Knock', '/api/spells/knock');
INSERT INTO spells (index, name, url) VALUES ('legend-lore', 'Legend Lore', '/api/spells/legend-lore');
INSERT INTO spells (index, name, url) VALUES ('lesser-restoration', 'Lesser Restoration', '/api/spells/lesser-restoration');
INSERT INTO spells (index, name, url) VALUES ('levitate', 'Levitate', '/api/spells/levitate');
INSERT INTO spells (index, name, url) VALUES ('light', 'Light', '/api/spells/light');
INSERT INTO spells (index, name, url) VALUES ('lightning-bolt', 'Lightning Bolt', '/api/spells/lightning-bolt');
INSERT INTO spells (index, name, url) VALUES ('locate-animals-or-plants', 'Locate Animals or Plants', '/api/spells/locate-animals-or-plants');
INSERT INTO spells (index, name, url) VALUES ('locate-creature', 'Locate Creature', '/api/spells/locate-creature');
INSERT INTO spells (index, name, url) VALUES ('locate-object', 'Locate Object', '/api/spells/locate-object');
INSERT INTO spells (index, name, url) VALUES ('longstrider', 'Longstrider', '/api/spells/longstrider');
INSERT INTO spells (index, name, url) VALUES ('mage-armor', 'Mage Armor', '/api/spells/mage-armor');
INSERT INTO spells (index, name, url) VALUES ('mage-hand', 'Mage Hand', '/api/spells/mage-hand');
INSERT INTO spells (index, name, url) VALUES ('magic-circle', 'Magic Circle', '/api/spells/magic-circle');
INSERT INTO spells (index, name, url) VALUES ('magic-jar', 'Magic Jar', '/api/spells/magic-jar');
INSERT INTO spells (index, name, url) VALUES ('magic-missile', 'Magic Missile', '/api/spells/magic-missile');
INSERT INTO spells (index, name, url) VALUES ('magic-mouth', 'Magic Mouth', '/api/spells/magic-mouth');
INSERT INTO spells (index, name, url) VALUES ('magic-weapon', 'Magic Weapon', '/api/spells/magic-weapon');
INSERT INTO spells (index, name, url) VALUES ('magnificent-mansion', 'Magnificent Mansion', '/api/spells/magnificent-mansion');
INSERT INTO spells (index, name, url) VALUES ('major-image', 'Major Image', '/api/spells/major-image');
INSERT INTO spells (index, name, url) VALUES ('mass-cure-wounds', 'Mass Cure Wounds', '/api/spells/mass-cure-wounds');
INSERT INTO spells (index, name, url) VALUES ('mass-heal', 'Mass Heal', '/api/spells/mass-heal');
INSERT INTO spells (index, name, url) VALUES ('mass-healing-word', 'Mass Healing Word', '/api/spells/mass-healing-word');
INSERT INTO spells (index, name, url) VALUES ('mass-suggestion', 'Mass Suggestion', '/api/spells/mass-suggestion');
INSERT INTO spells (index, name, url) VALUES ('maze', 'Maze', '/api/spells/maze');
INSERT INTO spells (index, name, url) VALUES ('meld-into-stone', 'Meld Into Stone', '/api/spells/meld-into-stone');
INSERT INTO spells (index, name, url) VALUES ('mending', 'Mending', '/api/spells/mending');
INSERT INTO spells (index, name, url) VALUES ('message', 'Message', '/api/spells/message');
INSERT INTO spells (index, name, url) VALUES ('meteor-swarm', 'Meteor Swarm', '/api/spells/meteor-swarm');
INSERT INTO spells (index, name, url) VALUES ('mind-blank', 'Mind Blank', '/api/spells/mind-blank');
INSERT INTO spells (index, name, url) VALUES ('minor-illusion', 'Minor Illusion', '/api/spells/minor-illusion');
INSERT INTO spells (index, name, url) VALUES ('mirage-arcane', 'Mirage Arcane', '/api/spells/mirage-arcane');
INSERT INTO spells (index, name, url) VALUES ('mirror-image', 'Mirror Image', '/api/spells/mirror-image');
INSERT INTO spells (index, name, url) VALUES ('mislead', 'Mislead', '/api/spells/mislead');
INSERT INTO spells (index, name, url) VALUES ('misty-step', 'Misty Step', '/api/spells/misty-step');
INSERT INTO spells (index, name, url) VALUES ('modify-memory', 'Modify Memory', '/api/spells/modify-memory');
INSERT INTO spells (index, name, url) VALUES ('moonbeam', 'Moonbeam', '/api/spells/moonbeam');
INSERT INTO spells (index, name, url) VALUES ('move-earth', 'Move Earth', '/api/spells/move-earth');
INSERT INTO spells (index, name, url) VALUES ('nondetection', 'Nondetection', '/api/spells/nondetection');
INSERT INTO spells (index, name, url) VALUES ('pass-without-trace', 'Pass Without Trace', '/api/spells/pass-without-trace');
INSERT INTO spells (index, name, url) VALUES ('passwall', 'Passwall', '/api/spells/passwall');
INSERT INTO spells (index, name, url) VALUES ('phantasmal-killer', 'Phantasmal Killer', '/api/spells/phantasmal-killer');
INSERT INTO spells (index, name, url) VALUES ('phantom-steed', 'Phantom Steed', '/api/spells/phantom-steed');
INSERT INTO spells (index, name, url) VALUES ('planar-ally', 'Planar Ally', '/api/spells/planar-ally');
INSERT INTO spells (index, name, url) VALUES ('planar-binding', 'Planar Binding', '/api/spells/planar-binding');
INSERT INTO spells (index, name, url) VALUES ('plane-shift', 'Plane Shift', '/api/spells/plane-shift');
INSERT INTO spells (index, name, url) VALUES ('plant-growth', 'Plant Growth', '/api/spells/plant-growth');
INSERT INTO spells (index, name, url) VALUES ('poison-spray', 'Poison Spray', '/api/spells/poison-spray');
INSERT INTO spells (index, name, url) VALUES ('polymorph', 'Polymorph', '/api/spells/polymorph');
INSERT INTO spells (index, name, url) VALUES ('power-word-kill', 'Power Word Kill', '/api/spells/power-word-kill');
INSERT INTO spells (index, name, url) VALUES ('power-word-stun', 'Power Word Stun', '/api/spells/power-word-stun');
INSERT INTO spells (index, name, url) VALUES ('prayer-of-healing', 'Prayer of Healing', '/api/spells/prayer-of-healing');
INSERT INTO spells (index, name, url) VALUES ('prestidigitation', 'Prestidigitation', '/api/spells/prestidigitation');
INSERT INTO spells (index, name, url) VALUES ('prismatic-spray', 'Prismatic Spray', '/api/spells/prismatic-spray');
INSERT INTO spells (index, name, url) VALUES ('prismatic-wall', 'Prismatic Wall', '/api/spells/prismatic-wall');
INSERT INTO spells (index, name, url) VALUES ('private-sanctum', 'Private Sanctum', '/api/spells/private-sanctum');
INSERT INTO spells (index, name, url) VALUES ('produce-flame', 'Produce Flame', '/api/spells/produce-flame');
INSERT INTO spells (index, name, url) VALUES ('programmed-illusion', 'Programmed Illusion', '/api/spells/programmed-illusion');
INSERT INTO spells (index, name, url) VALUES ('project-image', 'Project Image', '/api/spells/project-image');
INSERT INTO spells (index, name, url) VALUES ('protection-from-energy', 'Protection From Energy', '/api/spells/protection-from-energy');
INSERT INTO spells (index, name, url) VALUES ('protection-from-evil-and-good', 'Protection from Evil and Good', '/api/spells/protection-from-evil-and-good');
INSERT INTO spells (index, name, url) VALUES ('protection-from-poison', 'Protection from Poison', '/api/spells/protection-from-poison');
INSERT INTO spells (index, name, url) VALUES ('purify-food-and-drink', 'Purify Food and Drink', '/api/spells/purify-food-and-drink');
INSERT INTO spells (index, name, url) VALUES ('raise-dead', 'Raise Dead', '/api/spells/raise-dead');
INSERT INTO spells (index, name, url) VALUES ('ray-of-enfeeblement', 'Ray of Enfeeblement', '/api/spells/ray-of-enfeeblement');
INSERT INTO spells (index, name, url) VALUES ('ray-of-frost', 'Ray of Frost', '/api/spells/ray-of-frost');
INSERT INTO spells (index, name, url) VALUES ('regenerate', 'Regenerate', '/api/spells/regenerate');
INSERT INTO spells (index, name, url) VALUES ('reincarnate', 'Reincarnate', '/api/spells/reincarnate');
INSERT INTO spells (index, name, url) VALUES ('remove-curse', 'Remove Curse', '/api/spells/remove-curse');
INSERT INTO spells (index, name, url) VALUES ('resilient-sphere', 'Resilient Sphere', '/api/spells/resilient-sphere');
INSERT INTO spells (index, name, url) VALUES ('resistance', 'Resistance', '/api/spells/resistance');
INSERT INTO spells (index, name, url) VALUES ('resurrection', 'Resurrection', '/api/spells/resurrection');
INSERT INTO spells (index, name, url) VALUES ('reverse-gravity', 'Reverse Gravity', '/api/spells/reverse-gravity');
INSERT INTO spells (index, name, url) VALUES ('revivify', 'Revivify', '/api/spells/revivify');
INSERT INTO spells (index, name, url) VALUES ('rope-trick', 'Rope Trick', '/api/spells/rope-trick');
INSERT INTO spells (index, name, url) VALUES ('sacred-flame', 'Sacred Flame', '/api/spells/sacred-flame');
INSERT INTO spells (index, name, url) VALUES ('sanctuary', 'Sanctuary', '/api/spells/sanctuary');
INSERT INTO spells (index, name, url) VALUES ('scorching-ray', 'Scorching Ray', '/api/spells/scorching-ray');
INSERT INTO spells (index, name, url) VALUES ('scrying', 'Scrying', '/api/spells/scrying');
INSERT INTO spells (index, name, url) VALUES ('secret-chest', 'Secret Chest', '/api/spells/secret-chest');
INSERT INTO spells (index, name, url) VALUES ('see-invisibility', 'See Invisibility', '/api/spells/see-invisibility');
INSERT INTO spells (index, name, url) VALUES ('seeming', 'Seeming', '/api/spells/seeming');
INSERT INTO spells (index, name, url) VALUES ('sending', 'Sending', '/api/spells/sending');
INSERT INTO spells (index, name, url) VALUES ('sequester', 'Sequester', '/api/spells/sequester');
INSERT INTO spells (index, name, url) VALUES ('shapechange', 'Shapechange', '/api/spells/shapechange');
INSERT INTO spells (index, name, url) VALUES ('shatter', 'Shatter', '/api/spells/shatter');
INSERT INTO spells (index, name, url) VALUES ('shield', 'Shield', '/api/spells/shield');
INSERT INTO spells (index, name, url) VALUES ('shield-of-faith', 'Shield of Faith', '/api/spells/shield-of-faith');
INSERT INTO spells (index, name, url) VALUES ('shillelagh', 'Shillelagh', '/api/spells/shillelagh');
INSERT INTO spells (index, name, url) VALUES ('shocking-grasp', 'Shocking Grasp', '/api/spells/shocking-grasp');
INSERT INTO spells (index, name, url) VALUES ('silence', 'Silence', '/api/spells/silence');
INSERT INTO spells (index, name, url) VALUES ('silent-image', 'Silent Image', '/api/spells/silent-image');
INSERT INTO spells (index, name, url) VALUES ('simulacrum', 'Simulacrum', '/api/spells/simulacrum');
INSERT INTO spells (index, name, url) VALUES ('sleep', 'Sleep', '/api/spells/sleep');
INSERT INTO spells (index, name, url) VALUES ('sleet-storm', 'Sleet Storm', '/api/spells/sleet-storm');
INSERT INTO spells (index, name, url) VALUES ('slow', 'Slow', '/api/spells/slow');
INSERT INTO spells (index, name, url) VALUES ('spare-the-dying', 'Spare the Dying', '/api/spells/spare-the-dying');
INSERT INTO spells (index, name, url) VALUES ('speak-with-animals', 'Speak with Animals', '/api/spells/speak-with-animals');
INSERT INTO spells (index, name, url) VALUES ('speak-with-dead', 'Speak with Dead', '/api/spells/speak-with-dead');
INSERT INTO spells (index, name, url) VALUES ('speak-with-plants', 'Speak with Plants', '/api/spells/speak-with-plants');
INSERT INTO spells (index, name, url) VALUES ('spider-climb', 'Spider Climb', '/api/spells/spider-climb');
INSERT INTO spells (index, name, url) VALUES ('spike-growth', 'Spike Growth', '/api/spells/spike-growth');
INSERT INTO spells (index, name, url) VALUES ('spirit-guardians', 'Spirit Guardians', '/api/spells/spirit-guardians');
INSERT INTO spells (index, name, url) VALUES ('spiritual-weapon', 'Spiritual Weapon', '/api/spells/spiritual-weapon');
INSERT INTO spells (index, name, url) VALUES ('stinking-cloud', 'Stinking Cloud', '/api/spells/stinking-cloud');
INSERT INTO spells (index, name, url) VALUES ('stone-shape', 'Stone Shape', '/api/spells/stone-shape');
INSERT INTO spells (index, name, url) VALUES ('stoneskin', 'Stoneskin', '/api/spells/stoneskin');
INSERT INTO spells (index, name, url) VALUES ('storm-of-vengeance', 'Storm of Vengeance', '/api/spells/storm-of-vengeance');
INSERT INTO spells (index, name, url) VALUES ('suggestion', 'Suggestion', '/api/spells/suggestion');
INSERT INTO spells (index, name, url) VALUES ('sunbeam', 'Sunbeam', '/api/spells/sunbeam');
INSERT INTO spells (index, name, url) VALUES ('sunburst', 'Sunburst', '/api/spells/sunburst');
INSERT INTO spells (index, name, url) VALUES ('symbol', 'Symbol', '/api/spells/symbol');
INSERT INTO spells (index, name, url) VALUES ('telekinesis', 'Telekinesis', '/api/spells/telekinesis');
INSERT INTO spells (index, name, url) VALUES ('telepathic-bond', 'Telepathic Bond', '/api/spells/telepathic-bond');
INSERT INTO spells (index, name, url) VALUES ('teleport', 'Teleport', '/api/spells/teleport');
INSERT INTO spells (index, name, url) VALUES ('teleportation-circle', 'Teleportation Circle', '/api/spells/teleportation-circle');
INSERT INTO spells (index, name, url) VALUES ('thaumaturgy', 'Thaumaturgy', '/api/spells/thaumaturgy');
INSERT INTO spells (index, name, url) VALUES ('thunderwave', 'Thunderwave', '/api/spells/thunderwave');
INSERT INTO spells (index, name, url) VALUES ('time-stop', 'Time Stop', '/api/spells/time-stop');
INSERT INTO spells (index, name, url) VALUES ('tiny-hut', 'Tiny Hut', '/api/spells/tiny-hut');
INSERT INTO spells (index, name, url) VALUES ('tongues', 'Tongues', '/api/spells/tongues');
INSERT INTO spells (index, name, url) VALUES ('transport-via-plants', 'Transport via Plants', '/api/spells/transport-via-plants');
INSERT INTO spells (index, name, url) VALUES ('tree-stride', 'Tree Stride', '/api/spells/tree-stride');
INSERT INTO spells (index, name, url) VALUES ('true-polymorph', 'True Polymorph', '/api/spells/true-polymorph');
INSERT INTO spells (index, name, url) VALUES ('true-resurrection', 'True Resurrection', '/api/spells/true-resurrection');
INSERT INTO spells (index, name, url) VALUES ('true-seeing', 'True Seeing', '/api/spells/true-seeing');
INSERT INTO spells (index, name, url) VALUES ('true-strike', 'True Strike', '/api/spells/true-strike');
INSERT INTO spells (index, name, url) VALUES ('unseen-servant', 'Unseen Servant', '/api/spells/unseen-servant');
INSERT INTO spells (index, name, url) VALUES ('vampiric-touch', 'Vampiric Touch', '/api/spells/vampiric-touch');
INSERT INTO spells (index, name, url) VALUES ('vicious-mockery', 'Vicious Mockery', '/api/spells/vicious-mockery');
INSERT INTO spells (index, name, url) VALUES ('wall-of-fire', 'Wall of Fire', '/api/spells/wall-of-fire');
INSERT INTO spells (index, name, url) VALUES ('wall-of-force', 'Wall of Force', '/api/spells/wall-of-force');
INSERT INTO spells (index, name, url) VALUES ('wall-of-ice', 'Wall of Ice', '/api/spells/wall-of-ice');
INSERT INTO spells (index, name, url) VALUES ('wall-of-stone', 'Wall of Stone', '/api/spells/wall-of-stone');
INSERT INTO spells (index, name, url) VALUES ('wall-of-thorns', 'Wall of Thorns', '/api/spells/wall-of-thorns');
INSERT INTO spells (index, name, url) VALUES ('warding-bond', 'Warding Bond', '/api/spells/warding-bond');
INSERT INTO spells (index, name, url) VALUES ('water-breathing', 'Water Breathing', '/api/spells/water-breathing');
INSERT INTO spells (index, name, url) VALUES ('water-walk', 'Water Walk', '/api/spells/water-walk');
INSERT INTO spells (index, name, url) VALUES ('web', 'Web', '/api/spells/web');
INSERT INTO spells (index, name, url) VALUES ('weird', 'Weird', '/api/spells/weird');
INSERT INTO spells (index, name, url) VALUES ('wind-walk', 'Wind Walk', '/api/spells/wind-walk');
INSERT INTO spells (index, name, url) VALUES ('wind-wall', 'Wind Wall', '/api/spells/wind-wall');
INSERT INTO spells (index, name, url) VALUES ('wish', 'Wish', '/api/spells/wish');
INSERT INTO spells (index, name, url) VALUES ('word-of-recall', 'Word of Recall', '/api/spells/word-of-recall');
INSERT INTO spells (index, name, url) VALUES ('zone-of-truth', 'Zone of Truth', '/api/spells/zone-of-truth');

INSERT INTO wizards (name, spell_id) VALUES ('Clortho', 'acid-arrow');
INSERT INTO wizards (name, spell_id) VALUES ('Maxwell', 'magnificent-mansion');
INSERT INTO wizards (name, spell_id) VALUES ('Merlin', 'sunbeam');
INSERT INTO wizards (name, spell_id) VALUES ('Marry', 'dream');
INSERT INTO wizards (name, spell_id) VALUES ('Chuck', 'acid-arrow');
